name: Question
description: Ask a question about the mod
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any extra context that might help answer your question.
